### ISSUE TITLE
Update to Deforum Stable Diffusion version 0.5

### ISSUE THREAD

**Issue by Brackarnwar** [HelixNGC7293/DeforumStableDiffusionLocal#28]
Hello, it would be very cool to update to the last version of deforum stable diffusion. I am a developper myself, but i have little to no experience with google collab, and how the local version was done. if @HelixNGC7293, you have some hints about what you have done to achieve that, it would be great. If anyone is up to make it happen, here we can exchange how it can be done.

**Comment by everyoneishappy** [comment]
Was also curious about the process

**Comment by CognitiveTwo** [comment]
second :) this would be much appreciated!

**Comment by pablopub** [comment]
I've been using Deforum v0.5 on Jupyter-lab. It's a bit finicky with VRAM (having to restart the engine after canceling the current run, on my RTX 3070 ti 8 GB), but otherwise, I like the experience a lot.

**Comment by pancakez3d** [comment]
Would also second this! this local deforum version is by far the best one to work with imo. Would be amazing to have the 0.5 update for it <3

**Comment by f-rank** [comment]
> I've been using Deforum v0.5 on Jupyter-lab. It's a bit finicky with VRAM (having to restart the engine after canceling the current run, on my RTX 3070 ti 8 GB), but otherwise, I like the experience a lot. It even resumes without a problem after having slept and woken up the computer.

If you install xformers and swap out the new attention.py he got up in the repository. You won't have to restart after cancelling and bigger sized frames are possible. Please note that xformers introduces variant results for the same starting info. If you can live with that, it's a great speed bump too.

On my 3070 8 GB I had to restart the computer each time I finished one generation because it became unworkable and the engine wouldn't start a second generation. Now it's all good.

**Comment by pablopub** [comment]
> > I've been using Deforum v0.5 on Jupyter-lab. It's a bit finicky with VRAM (having to restart the engine after canceling the current run, on my RTX 3070 ti 8 GB), but otherwise, I like the experience a lot. It even resumes without a problem after having slept and woken up the computer.
> 
> If you install xformers and swap out the new attention.py he got up in the repository. You won't have to restart after cancelling and bigger sized frames are possible. Please note that xformers introduces variant results for the same starting info. If you can live with that, it's a great speed bump too.
> 
> On my 3070 8 GB (laptop) I had to restart the computer each time I finished one generation because it became unworkable and the engine wouldn't start a second generation. Now it's all good.

Hello! Thank you for your tips! I will try them sure!

However, I want to tell you about my current situation. What allowed me to get rid of the OOM error with Deforum v0.5 is to run gc.collect() and torch.cuda.empty_cache() before every run (I think those commands are also run after successful completion, but in order to fine-tune I canceled more times than not).

That's not to say that bigger-sized frames and a speedier DSD wouldn't be great!

Thanks again and have a nice day!

**Comment by bilols** [comment]
For the ability to use math functions, 0.5 is an absolute necessity.

**Comment by amithgc** [comment]
here the the local version which supports deforum v0.5
[deforum-0.5-local](https://github.com/amithgc/DeforumStableDiffusion-v0.5-Local)

**Comment by bilols** [comment]
> here the the local version which supports deforum v0.5 [deforum-0.5-local](https://github.com/amithgc/DeforumStableDiffusion-v0.5-Local)

Thanks. I'm trying it out now. I was actually going to update tomorrow and try to get it working with 0.5 and you saved me a load of time.

**Comment by bilols** [comment]
> here the the local version which supports deforum v0.5 [deforum-0.5-local](https://github.com/amithgc/DeforumStableDiffusion-v0.5-Local)

Works great. Folks need to use the new 0.5 settings format, but I was able to render using my nvidia 3090, 3060, and 2070. Thank you very much, Amith.
